(ns llm-context.source-role
  "Repository-neutral source-role classification and stable retrieval preference."
  (:require [clojure.string :as str]))

(def preferences #{:auto :production :test :none})
(def roles #{:production :test :generated :vendor :unknown})

(def ^:private test-segments
  #{"test" "tests" "spec" "specs" "__tests__"})

(def ^:private generated-segments
  #{"generated" "gen" "autogen" "autogenerated"})

(def ^:private vendor-segments
  #{"vendor" "vendors" "third_party" "third-party" "node_modules"})

(def ^:private test-file-pattern
  #"(?i)(?:^|/)(?:test|spec)[_-][^/]+\.[^/]+$|(?:^|/)[^/]+(?:[_-](?:test|spec)|\.(?:test|spec))\.[^/]+$")

(def ^:private explicit-test-intent-pattern
  #"(?i)\b(?:test|tests|testing|spec|specs|fixture|fixtures)\b")

(defn normalize-preference [value]
  (let [normalized (cond
                     (keyword? value) value
                     (string? value) (keyword (str/lower-case value))
                     (nil? value) :none
                     :else value)]
    (if (contains? preferences normalized)
      normalized
      (throw
       (ex-info
        "Source preference must be one of auto, production, test, or none"
        {:exit-code 2 :source-preference value})))))

(defn- normalized-path [file]
  (some-> file str (str/replace "\\" "/") str/lower-case))

(defn- glob-regex [pattern]
  (let [pattern (normalized-path pattern)
        length (count pattern)]
    (re-pattern
     (str
      "^"
      (loop [index 0 result (StringBuilder.)]
        (if (>= index length)
          (str result)
          (let [character (.charAt pattern index)
                next-character (when (< (inc index) length)
                                 (.charAt pattern (inc index)))]
            (cond
              (and (= character \*) (= next-character \*)
                   (< (+ index 2) length)
                   (= \/ (.charAt pattern (+ index 2))))
              (recur (+ index 3) (.append result "(?:.*/)?"))

              (and (= character \*) (= next-character \*))
              (recur (+ index 2) (.append result ".*"))

              (= character \*)
              (recur (inc index) (.append result "[^/]*"))

              (= character \?)
              (recur (inc index) (.append result "[^/]"))

              (contains? #{\. \+ \( \) \[ \] \{ \} \^ \$ \| \\} character)
              (recur (inc index) (doto result (.append \\) (.append character)))

              :else
              (recur (inc index) (.append result character))))))
      "$"))))

(def ^:private cached-glob-regex (memoize glob-regex))

(defn- override-role [file overrides]
  (some
   (fn [{:keys [role pattern]}]
     (when (and (contains? roles role)
                (string? pattern)
                (re-matches (cached-glob-regex pattern) file))
       role))
   overrides))

(defn classify
  "Classify one canonical repository-relative file path. Ordered project
  overrides use simple glob syntax and take precedence over built-in rules."
  ([file] (classify file []))
  ([file overrides]
   (let [file (normalized-path file)
         segments (when (seq file) (str/split file #"/"))
         override (when (seq file) (override-role file overrides))]
     (cond
       (not (seq file)) :unknown
       override override
       (some vendor-segments segments) :vendor
       (some generated-segments segments) :generated
       (or (some test-segments segments)
           (re-find test-file-pattern file)) :test
       :else :production))))

(defn resolve-preference [requested query]
  (let [requested (normalize-preference requested)]
    (if (= :auto requested)
      (if (re-find explicit-test-intent-pattern (or query ""))
        {:requested :auto :resolved :test :reason :explicit-test-intent}
        {:requested :auto :resolved :production :reason :general-implementation-query})
      {:requested requested :resolved requested :reason :explicit-preference})))

(defn- exact-result? [query result]
  (contains? (set (remove nil? ((juxt :id :name :qualified-name) result))) query))

(defn- preferred-role? [preference role]
  (case preference
    :production (= :production role)
    :test (= :test role)
    false))

(defn prefer
  "Annotate fused results with source roles and stably apply a source
  preference. Exact identifier matches always retain priority. Scores are not
  changed; fused and final ranks make policy ordering explicit."
  [results query requested overrides]
  (let [{:keys [resolved] :as resolution} (resolve-preference requested query)
        annotated
        (mapv (fn [rank result]
                (assoc result
                       :source-role (classify (:file result) overrides)
                       :fused-rank rank))
              (range 1 (inc (count results))) results)
        [exact non-exact] ((juxt filter remove) #(exact-result? query %) annotated)
        ordered-non-exact
        (if (contains? #{:production :test} resolved)
          (let [[preferred other]
                ((juxt filter remove)
                 #(preferred-role? resolved (:source-role %)) non-exact)]
            (concat preferred other))
          non-exact)
        ordered (vec (concat exact ordered-non-exact))
        final-results
        (mapv (fn [rank result]
                (cond-> (assoc result :final-rank rank)
                  (not= rank (:fused-rank result))
                  (assoc :ranking-reason
                         (if (preferred-role? resolved (:source-role result))
                           (keyword (str (name resolved) "-preferred"))
                           :source-preference-demotion))))
              (range 1 (inc (count ordered))) ordered)
        role-counts (frequencies (map :source-role annotated))]
    {:results final-results
     :resolution resolution
     :role-counts role-counts
     :reordered? (not= (mapv :id annotated) (mapv :id final-results))}))
